import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "../../components/Footer";
import "bootstrap/dist/css/bootstrap.min.css";
import styles from './page.module.css'
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (

    <html lang="en">
        <Footer></Footer>
      <body className={inter.className}>{children}</body>
     
    </html>

  );
}
